name: Check Nix flake
on: [push, pull_request]

permissions:
  checks: write

jobs:
  nix:
    name: Check Nix flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Build default flake output
        run: nix build
